---
title: "The Impact of Gender on Perception of Risk During Exercise"
output: html_notebook
---


```{r}
library(tidyverse)
library(gapminder)
library(socviz)
library(ggplot2)
library(gganimate)
library(gifski)
library(png)
library(lubridate)
```

```{r}
Gender <- c("Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Female", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male")
HoursExercising <- c("0 -1 Hour", "0 -1 Hour","0 -1 Hour","0 -1 Hour","0 -1 Hour","0 -1 Hour","0 -1 Hour","0 -1 Hour","0 -1 Hour","0 -1 Hour", "0 -1 Hour", "0 -1 Hour","0 -1 Hour","0 -1 Hour","0 -1 Hour","0 -1 Hour","0 -1 Hour","0 -1 Hour","0 -1 Hour","0 -1 Hour","0 -1 Hour", "0 -1 Hour","0 -1 Hour","0 -1 Hour","0 -1 Hour","0 -1 Hour","0 -1 Hour","0 -1 Hour","0 -1 Hour","0 -1 Hour","0 -1 Hour","0 -1 Hour","0 -1 Hour","1-3 hours","1-3 hours","1-3 hours","1-3 hours","1-3 hours","1-3 hours","1-3 hours","1-3 hours","1-3 hours","1-3 hours","1-3 hours","1-3 hours","1-3 hours","1-3 hours","1-3 hours","1-3 hours","1-3 hours","1-3 hours","1-3 hours","1-3 hours","1-3 hours","1-3 hours","1-3 hours","1-3 hours","1-3 hours","1-3 hours","1-3 hours","1-3 hours","1-3 hours","1-3 hours","1-3 hours","1-3 hours","1-3 hours","1-3 hours","1-3 hours","1-3 hours","1-3 hours","1-3 hours","1-3 hours","4-6 hours","4-6 hours","4-6 hours","4-6 hours","4-6 hours","4-6 hours","4-6 hours","4-6 hours","4-6 hours","4-6 hours","4-6 hours","4-6 hours","4-6 hours","4-6 hours","4-6 hours","4-6 hours","4-6 hours","4-6 hours","4-6 hours","4-6 hours","4-6 hours","4-6 hours","4-6 hours","4-6 hours","4-6 hours","4-6 hours","4-6 hours","4-6 hours","4-6 hours","4-6 hours","4-6 hours","4-6 hours","4-6 hours","4-6 hours","4-6 hours","4-6 hours","4-6 hours","4-6 hours","4-6 hours","4-6 hours","7-9 hours","7-9 hours","7-9 hours","7-9 hours","7-9 hours","7-9 hours","7-9 hours","7-9 hours","7-9 hours","7-9 hours","7-9 hours","7-9 hours","7-9 hours","7-9 hours","Plus 10","Plus 10","Plus 10","Plus 10","Plus 10","Plus 10","0 -1 Hour", "0 -1 Hour","0 -1 Hour","0 -1 Hour","0 -1 Hour","0 -1 Hour","0 -1 Hour","0 -1 Hour","0 -1 Hour","1-3 hours","1-3 hours","1-3 hours","1-3 hours","1-3 hours","1-3 hours","1-3 hours","1-3 hours","1-3 hours","1-3 hours","1-3 hours","1-3 hours","1-3 hours","1-3 hours","1-3 hours","1-3 hours","1-3 hours","1-3 hours","1-3 hours","1-3 hours","1-3 hours","1-3 hours","1-3 hours","1-3 hours","1-3 hours","1-3 hours","1-3 hours","4-6 hours","4-6 hours","4-6 hours","4-6 hours","4-6 hours","4-6 hours","4-6 hours","4-6 hours","4-6 hours","4-6 hours","4-6 hours","4-6 hours","4-6 hours","4-6 hours","4-6 hours","4-6 hours","4-6 hours","4-6 hours","4-6 hours","4-6 hours","4-6 hours","4-6 hours","4-6 hours","4-6 hours","7-9 hours","7-9 hours","7-9 hours","7-9 hours","7-9 hours","7-9 hours","7-9 hours","7-9 hours","7-9 hours","7-9 hours","7-9 hours","7-9 hours","7-9 hours","7-9 hours","7-9 hours","7-9 hours","7-9 hours","7-9 hours","7-9 hours","7-9 hours","7-9 hours","7-9 hours","Plus 10","Plus 10","Plus 10","Plus 10","Plus 10","Plus 10","Plus 10","Plus 10","Plus 10","Plus 10","Plus 10","Plus 10","Plus 10","Plus 10","Plus 10","Plus 10","Plus 10","Plus 10")
RecCenter_part <- c("Basketball Courts", "Basketball Courts","Basketball Courts","Basketball Courts","Basketball Courts","Basketball Courts","Basketball Courts","Basketball Courts","Basketball Courts","Basketball Courts","Basketball Courts","Basketball Courts","Basketball Courts","Basketball Courts","Basketball Courts","Basketball Courts","Basketball Courts","Indoor Lap Pool","Indoor Lap Pool","Indoor Lap Pool","Indoor Lap Pool","Indoor Lap Pool","Indoor Lap Pool","Indoor Lap Pool","Indoor Lap Pool","Indoor Lap Pool","Indoor Lap Pool","Indoor Lap Pool","Indoor Lap Pool","Indoor Lap Pool","Indoor Lap Pool","Indoor Lap Pool","Indoor Lap Pool","Indoor Lap Pool","Indoor Lap Pool","Indoor Lap Pool","Indoor Lap Pool","Indoor Lap Pool","Indoor Lap Pool","Free Weights", "Free Weights","Free Weights","Free Weights","Free Weights","Free Weights","Free Weights","Free Weights","Free Weights","Free Weights","Free Weights","Free Weights","Free Weights","Free Weights","Free Weights","Free Weights","Free Weights","Free Weights","Free Weights","Free Weights","Free Weights","Free Weights","Free Weights","Free Weights","Free Weights", "Machine Weights","Machine Weights","Machine Weights","Machine Weights","Machine Weights","Machine Weights","Machine Weights","Machine Weights","Machine Weights","Machine Weights","Machine Weights","Machine Weights","Machine Weights","Machine Weights","Machine Weights","Machine Weights", "Cardio Machines","Cardio Machines","Cardio Machines","Cardio Machines","Cardio Machines","Cardio Machines","Cardio Machines","Cardio Machines","Cardio Machines","Cardio Machines","Cardio Machines","Cardio Machines","Cardio Machines","Cardio Machines","Cardio Machines","Cardio Machines","Cardio Machines","Cardio Machines","Cardio Machines","Cardio Machines","Cardio Machines","Cardio Machines","Cardio Machines","Cardio Machines","Cardio Machines","Cardio Machines","Cardio Machines","Cardio Machines","Cardio Machines","Cardio Machines","Cardio Machines","Cardio Machines","Cardio Machines","Cardio Machines","Cardio Machines","Cardio Machines","Cardio Machines","Cardio Machines","Cardio Machines","Cardio Machines","Cardio Machines","Cardio Machines","Cardio Machines","Cardio Machines","Cardio Machines","Cardio Machines","Cardio Machines","Cardio Machines","Cardio Machines","Rock Climbing", "Rock Climbing", "Rock Climbing","Basketball Courts", "Basketball Courts","Basketball Courts","Basketball Courts","Basketball Courts","Basketball Courts","Basketball Courts","Basketball Courts","Basketball Courts","Basketball Courts","Basketball Courts", "Basketball Courts","Basketball Courts","Basketball Courts","Basketball Courts","Basketball Courts","Basketball Courts","Basketball Courts","Basketball Courts","Indoor Lap Pool","Indoor Lap Pool","Indoor Lap Pool","Indoor Lap Pool","Free Weights", "Free Weights","Free Weights","Free Weights","Free Weights","Free Weights","Free Weights","Free Weights","Free Weights","Free Weights","Free Weights","Free Weights","Free Weights","Free Weights","Free Weights","Free Weights","Free Weights","Free Weights","Free Weights","Free Weights","Free Weights","Free Weights","Free Weights","Free Weights","Free Weights","Free Weights","Free Weights","Free Weights","Free Weights","Free Weights","Free Weights","Free Weights","Free Weights","Free Weights","Free Weights","Free Weights","Free Weights","Free Weights","Machine Weights","Machine Weights","Machine Weights","Machine Weights","Machine Weights","Machine Weights","Machine Weights","Machine Weights","Machine Weights","Machine Weights","Machine Weights","Machine Weights","Machine Weights","Machine Weights","Machine Weights","Machine Weights","Machine Weights","Machine Weights","Machine Weights","Machine Weights","Machine Weights", "Cardio Machines","Cardio Machines","Cardio Machines","Cardio Machines","Cardio Machines","Cardio Machines","Cardio Machines","Cardio Machines","Cardio Machines","Cardio Machines","Cardio Machines", "Rock Climbing","Rock Climbing","Rock Climbing","Rock Climbing","Rock Climbing","Rock Climbing","Rock Climbing")
Supervisors <- c("0-2", "0-2", "0-2", "0-2", "0-2", "0-2", "0-2", "0-2", "0-2", "0-2", "0-2", "0-2", "0-2", "0-2", "0-2", "0-2", "0-2", "0-2", "0-2", "0-2", "0-2", "0-2", "0-2", "0-2", "0-2", "0-2", "0-2", "0-2", "0-2", "0-2", "0-2", "0-2", "0-2", "0-2", "0-2", "0-2", "0-2", "0-2", "0-2", "0-2", "0-2", "0-2", "0-2", "0-2", "0-2", "0-2", "0-2", "2-4", "2-4", "2-4", "2-4", "2-4", "2-4", "2-4", "2-4", "2-4", "2-4", "2-4", "2-4", "2-4", "2-4", "2-4", "2-4", "2-4", "2-4", "2-4", "2-4", "2-4", "2-4", "2-4", "2-4", "2-4", "2-4", "2-4", "2-4", "2-4", "2-4", "2-4", "2-4", "2-4", "2-4", "2-4", "2-4", "2-4", "2-4", "2-4", "2-4", "2-4", "2-4", "2-4", "2-4", "2-4", "2-4", "2-4", "2-4", "2-4", "2-4", "2-4","4-6","4-6","4-6","4-6","4-6","4-6","4-6","4-6","4-6","4-6","4-6","4-6","4-6","4-6","4-6","4-6","4-6","4-6","4-6","4-6","4-6","4-6","6-8","6-8","6-8","6-8","6-8","6-8","8-10","8-10","8-10","Plus 10","Plus 10","Plus 10","0-2", "0-2", "0-2", "0-2", "0-2", "0-2", "0-2", "0-2", "0-2", "0-2","0-2", "0-2", "0-2", "0-2", "0-2", "0-2", "0-2", "0-2", "0-2", "0-2","0-2", "0-2", "0-2", "0-2", "0-2","2-4", "2-4", "2-4", "2-4", "2-4", "2-4", "2-4", "2-4", "2-4", "2-4","2-4", "2-4", "2-4", "2-4", "2-4", "2-4", "2-4", "2-4", "2-4", "2-4","2-4", "2-4", "2-4", "2-4", "2-4", "2-4", "2-4", "2-4", "2-4", "2-4","2-4", "2-4", "2-4", "2-4", "2-4", "2-4", "4-6","4-6","4-6","4-6","4-6","4-6","4-6","4-6","4-6","4-6","4-6","4-6","4-6","4-6","4-6","4-6","4-6","4-6","4-6","4-6","4-6","4-6","4-6","4-6","4-6","4-6","4-6","4-6","4-6","4-6","4-6","4-6","4-6","4-6","4-6","6-8","8-10","Plus 10","Plus 10")
```


```{r}
summary(Gender)
summary(HoursExercising)
summary(RecCenter_part)
summary(Supervisors)
```


```{r}
Risk_Perception <- data.frame(Gender,
                           HoursExercising,
                           RecCenter_part,
                           Supervisors)
```

# FIGURE #1
```{r}
# HOURS SPENT EXERCISING PER WEEK
ggplot(data = Risk_Perception, mapping = aes(x = HoursExercising, fill = Gender)) +
  geom_bar(position = "dodge", mapping = aes(y = ..count.., group = Gender)) +
  labs(x = NULL,
       y = "Count",
       fill = NULL, 
       title = "Hours Spent Exercising per Week.",
       caption = "Source: thesportsjournal.org") +
  geom_text(aes(label = ..count.., group = Gender),
            stat = "count",
            position = position_dodge(width = 1),
            vjust = -0.5, size = 4,
            inherit.aes = TRUE) +
  theme_bw() +
  theme(axis.text.x = element_text(face = "bold", size = 8)) +
  theme(axis.text.y = element_text(face = "bold", size = 8)) +
  theme(legend.position = "bottom") +
  transition_states(HoursExercising,
                    transition_length = 2,
                    state_length = 2)
```



# FIGURE #2
```{r}
# Most Used Part of the Rec Center
ggplot(data = Risk_Perception, mapping = aes(x = RecCenter_part, fill = Gender)) +
  geom_bar(position = "dodge", mapping = aes(y = ..count.., group = Gender)) +
  labs(x = NULL,
       y = "Count",
       fill = NULL, 
       title = "Most Used Part of the Recreation Center",
       caption = "Source: thesportsjournal.org") +
  geom_text(aes(label = ..count.., group = Gender),
            stat = "count",
            position = position_dodge(width = 1),
            hjust = -0.5, size = 4,
            inherit.aes = TRUE) +
  coord_flip()+
  theme_bw() +
  theme(axis.text.x = element_text(face = "bold", size = 8)) +
  theme(axis.text.y = element_text(face = "bold", size = 8)) +
  theme(legend.position = "bottom") +
  transition_states(RecCenter_part,
                    transition_length = 2,
                    state_length = 2)
```


# FIGURE #3
```{r}
# NUMBER OF SUPERVISORS SEEN AT TIME OF WORKOUT
ggplot(data = Risk_Perception, mapping = aes(x = Supervisors, fill = Gender)) +
  geom_bar(position = "dodge", mapping = aes(y = ..count.., group = Gender)) +
  labs(x = NULL,
       y = "Count",
       fill = NULL, 
       title = "Number of Supervisors Seen at time of Workout",
       caption = "Source: thesportsjournal.org") +
  geom_text(aes(label = ..count.., group = Gender),
            stat = "count",
            position = position_dodge(width = 1),
            vjust = -0.5, size = 4,
            inherit.aes = TRUE) +
  theme_bw() +
  theme(axis.text.x = element_text(face = "bold", size = 8)) +
  theme(axis.text.y = element_text(face = "bold", size = 8)) +
  theme(legend.position = "bottom") +
  transition_states(Supervisors,
                    transition_length = 2,
                    state_length = 2)
```




# LINK TO JOURNAL: The Impact of Gender on Perception of Risk During Exercise
https://thesportjournal.org/article/the-impact-of-gender-on-perception-of-risk-during-exercise/
